[tool.poetry]
name = "dl"
version = "0.1.0"
description = ""
authors = ["Sebastian Jitaru <sjitaru29@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.2.0"
kaggle = "^1.6.17"
torch = "^2.5.1"
pandas = "^2.2.3"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
